import { StyleSheet } from "react-native";

import { colors } from "@/ui/theme";

export const coreStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: { padding: 22, paddingBottom: 36 },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  eyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.6,
    marginBottom: 10,
  },
  heroTitle: {
    color: colors.ink,
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: -0.6,
    marginBottom: 8,
  },
  heroBody: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 24,
  },
  sectionHeading: { marginTop: 24, marginBottom: 10 },
  sectionHeadingRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: "800" },
  sectionDetail: { color: colors.muted, fontSize: 13, marginTop: 3 },
  typeCard: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  notificationCard: {
    backgroundColor: colors.warm,
    borderRadius: 18,
    marginTop: 18,
    padding: 16,
  },
  rowBetween: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  flexText: { flex: 1 },
  cardTitle: { color: colors.ink, fontSize: 16, fontWeight: "700" },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  fieldLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 8,
    marginTop: 16,
  },
  helper: { color: colors.muted, fontSize: 12, marginTop: 7 },
  tinyNote: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 10,
    textAlign: "center",
  },
  switch: {
    alignItems: "center",
    backgroundColor: colors.line,
    borderRadius: 20,
    justifyContent: "center",
    minWidth: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  switchOn: { backgroundColor: colors.accent },
  switchText: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  switchTextOn: { color: "#FFFFFF" },
  chipRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  chip: {
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chipSelected: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  chipText: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  chipTextSelected: { color: colors.accent },
  smallInput: {
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    minWidth: 70,
    paddingHorizontal: 10,
    paddingVertical: 9,
    textAlign: "center",
  },
  inputBox: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 13,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  rupeeInput: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    paddingLeft: 14,
  },
  rupeePrefix: { color: colors.muted, fontSize: 17, fontWeight: "700" },
  input: {
    color: colors.ink,
    flex: 1,
    fontSize: 17,
    paddingHorizontal: 10,
    paddingVertical: 11,
  },
  button: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: 14,
    justifyContent: "center",
    marginTop: 16,
    minHeight: 50,
    paddingHorizontal: 18,
  },
  buttonSecondary: {
    backgroundColor: "transparent",
    borderColor: colors.accent,
    borderWidth: 1,
  },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
  buttonSecondaryText: { color: colors.accent },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
  },
  flex: { flex: 1 },
  pressed: { opacity: 0.75 },
  error: { color: colors.danger, fontSize: 13, lineHeight: 19, marginTop: 14 },
  closeText: { color: colors.accent, fontSize: 13, fontWeight: "800" },
  empty: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
});
