import { StyleSheet } from "react-native";

import { colors } from "@/ui/theme";

export const deliveryStyles = StyleSheet.create({
  summaryCard: {
    backgroundColor: colors.accent,
    borderRadius: 20,
    marginBottom: 22,
    padding: 20,
  },
  summaryValue: { color: "#FFFFFF", fontSize: 30, fontWeight: "800" },
  summaryMuted: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    lineHeight: 19,
  },
  summaryBreakdown: {
    borderTopColor: "rgba(255,255,255,0.25)",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 24,
    marginTop: 18,
    paddingTop: 14,
  },
  breakdownItem: { flex: 1 },
  breakdownValue: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 2,
  },
  dateTitle: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  statusPill: {
    backgroundColor: colors.accentSoft,
    borderRadius: 20,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  statusText: { color: colors.accent, fontSize: 11, fontWeight: "800" },
  linesCard: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    padding: 16,
  },
  lineRow: {
    alignItems: "center",
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingBottom: 13,
    paddingTop: 2,
  },
  lineCost: { color: colors.ink, fontSize: 16, fontWeight: "800" },
  totalRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 15,
  },
  totalLabel: { color: colors.muted, fontSize: 13, fontWeight: "700" },
  totalValue: { color: colors.ink, fontSize: 21, fontWeight: "800" },
  monthNav: { alignItems: "center", flexDirection: "row", gap: 8 },
  monthNavButton: {
    alignItems: "center",
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    minWidth: 44,
  },
  monthNavButtonPressed: { backgroundColor: colors.accentSoft },
  monthNavArrow: { color: colors.accent, fontSize: 20, fontWeight: "700", lineHeight: 22 },
  calendarCard: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 4,
    padding: 12,
  },
  calendarWeekRow: {
    flexDirection: "row",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  calendarWeekday: {
    color: colors.muted,
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  calendarGrid: {
    gap: 6,
  },
  calendarRow: {
    flexDirection: "row",
    gap: 6,
  },
  calendarCell: {
    alignItems: "center",
    aspectRatio: 1,
    borderRadius: 10,
    flex: 1,
    justifyContent: "center",
  },
  calendarCellSelected: { backgroundColor: colors.accent },
  calendarCellToday: {
    borderColor: colors.accent,
    borderWidth: 1.5,
  },
  calendarCellFuture: { opacity: 0.3 },
  calendarDay: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  calendarDaySelected: { color: "#FFFFFF" },
  calendarDot: {
    borderRadius: 3,
    height: 6,
    marginTop: 3,
    width: 6,
  },
  calendarDotDefault: { backgroundColor: colors.muted, opacity: 0.5 },
  calendarDotEdited: { backgroundColor: colors.accent },
  calendarDotSelected: { backgroundColor: "#FFFFFF" },
  calendarDotNone: {
    backgroundColor: "transparent",
    borderColor: colors.line,
    borderWidth: 1,
  },
  calendarLegend: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
    paddingTop: 10,
  },
  calendarLegendItem: { alignItems: "center", flexDirection: "row", gap: 5 },
  calendarLegendText: { color: colors.muted, fontSize: 11 },
  dayDetailCard: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    padding: 16,
  },
  dayDetailStatus: {
    alignItems: "flex-end",
  },
  dayDetailLines: {
    marginTop: 6,
  },
  dayDetailLine: {
    alignItems: "center",
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingBottom: 11,
    paddingTop: 11,
  },
  dayDetailLineName: { color: colors.ink, flex: 1, fontSize: 14, fontWeight: "700" },
  dayDetailLineQuantity: { color: colors.muted, fontSize: 13, marginRight: 12 },
});
